title: The Reverser's Draft
author: moval0x1
email: moval0x1@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Coding & Malware & Reverse Engineering
show_excerpts: true # set to true to show excerpts on the homepage
#baseurl: /texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: The Reverser's Draft
  tagline: Coding & Malware & Reverse Engineering
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false
  disqus_shortname: games

  navigation:
    - title: Home
      url: "/"
      
  # generate social links in footer
  social_links:
    twitter: moval0x1
    github:  moval0x1
    linkedIn: in/charleslomboni
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed